contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #stitchimpute channel"
    url: https://nfcore.slack.com/channels/stitchimpute
    about: Discussion about the nf-core/stitchimpute pipeline
